# Generated by Django 3.1.7 on 2021-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210414_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-name'], 'verbose_name': 'Работодатель', 'verbose_name_plural': 'Работодатели'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-name'], 'verbose_name': 'Сотрудник университета', 'verbose_name_plural': 'Университет'},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='university',
            name='email',
        ),
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='initials',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
