# Generated by Django 3.1.7 on 2021-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210414_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='name_org',
            field=models.CharField(max_length=200, null=True, verbose_name='Название Организации'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Юзернейм'),
        ),
    ]
