# Generated by Django 3.1.7 on 2021-04-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vboard', '0003_auto_20210415_2004'),
        ('accounts', '0007_auto_20210414_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='my_skill',
            field=models.ManyToManyField(blank=True, to='vboard.Skill', verbose_name='Навыки'),
        ),
    ]
