# Generated by Django 3.1.7 on 2021-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vboard', '0002_auto_20210414_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=models.CharField(choices=[('U', 'university'), ('E', 'employer')], default='E', max_length=1, verbose_name='Создатель'),
        ),
    ]
